targets:
  $default:
    builders:
      slang_build_runner:
        enabled: true
        options:
          base_locale: en
      gitsumu|info:
        generate_for:
          - lib/utils/git_info.dart
      dart_mappable_builder:
        options:
          generatedMethods: [ decode, encode, copy, stringify, equals ]

