name: tsdm_client
description: 使用Flutter制作的天使动漫（tsdm39.com）论坛非官方客户端
repository: https://github.com/realth000/tsdm_client
homepage: https://github.com/realth000/tsdm_client
issue_tracker: https://github.com/realth000/tsdm_client/issues
publish_to: 'none'

version: 0.7.1+10

environment:
  flutter: ">=3.19.0 <4.0.0"
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  card_swiper: ^3.0.1
  change_case: ^2.0.1
  # Blocked by flutter
  collection: any
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.2.1
  # Blocked by appflow-editor
  device_info_plus: ^9.1.2
  dio: ^5.4.1
  dio_cookie_manager: ^3.1.1
  easy_refresh: ^3.3.4
  equatable: ^2.0.5
  extended_nested_scroll_view: ^6.2.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bbcode_editor:
    path: './packages/flutter_bbcode_editor'
    # git:
    #   url: https://github.com/realth000/flutter_bbcode_editor.git
    #   ref: fc03d1595adfa7d2e3b672e2407460c61699b82c
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.22
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  gitsumu: ^0.3.0
  go_router: ^13.2.1
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.8.1
  path: any
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  responsive_framework: ^1.4.0
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  stream_transform: ^2.1.0
  surf_lint_rules: ^3.0.0
  universal_html: ^2.2.4
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  dart_mappable_builder:
    git:
      url: https://github.com/realth000/dart_mappable
      path: "packages/dart_mappable_builder"
      ref: c57472c8fd2434d3eb5e100f7170d4c23b788610
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  slang_build_runner: ^3.30.0
  very_good_analysis: ^5.1.0

#  dependency_overrides:
#    # Blocked by custom_lint 0.5.3 and flutter_test
#    uuid: ^4.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/text/

# To generate png from svg, run:
# rsvg-convert -w 200 -h 300 tsdm_client.svg -o tsdm_client-large-200x300.png
flutter_launcher_icons:
  image_path: "assets/images/tsdm_client-large-300x300.png"
  ios: true
  macos:
    generate: true
    image_path: "assets/images/tsdm_client-large-300x300.png"
  windows:
    generate: true
    image_path: "assets/images/tsdm_client-large-300x300.png"

