name: tsdm_client
description: 使用Flutter制作的天使动漫（tsdm39.com）论坛非官方客户端
homepage: https://github.com/realth000/tsdm_client
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  collection: ^1.17.2
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  dio_image_provider: ^0.0.2
  easy_refresh: ^3.3.2+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.10.5+3
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  go_router: ^11.1.2
  hooks_riverpod: ^2.4.2
  html: ^0.15.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  riverpod_annotation: ^2.1.6
  shared_preferences: ^2.2.1
  surf_lint_rules: ^3.0.0
  url_launcher: ^6.1.14
  window_manager: ^0.3.6

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  lints: ^2.1.1
  riverpod_generator: ^3.0.0-dev.2
  riverpod_lint: ^2.2.1

flutter:
  uses-material-design: true
