name: tsdm_client
description: 使用Flutter制作的天使动漫（tsdm39.com）论坛非官方客户端
homepage: https://github.com/realth000/tsdm_client
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  # Blocked by flutter
  collection: ^1.17.2
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  easy_refresh: ^3.3.2+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_widget_from_html: ^0.14.4
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  hooks_riverpod: ^2.4.4
  html: ^0.15.4
  intl: ^0.18.1
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  responsive_framework: ^1.1.1
  riverpod_annotation: ^2.2.1
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  surf_lint_rules: ^3.0.0
  url_launcher: ^6.1.14
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  flutter_launcher_icons: ^0.13.1
  # Blocked by surf_lint_rules
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  # Blocked by surf_lint_rules
  lints: ^2.1.1
  riverpod_generator: ^3.0.0-dev.2
  riverpod_lint: ^2.3.2
  slang_build_runner: ^3.25.0

dependency_overrides:
  # Blocked by custom_lint 0.5.3
  uuid: ^4.1.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/images/tsdm_client.png"
  windows:
    generate: true
    image_path: "assets/images/tsdm_client.png"

