name: tsdm_client
description: 使用Flutter制作的天使动漫（tsdm39.com）论坛非官方客户端
repository: https://github.com/realth000/tsdm_client
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  # Blocked by flutter
  collection: any
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  easy_refresh: ^3.3.2+4
  extended_nested_scroll_view: ^6.1.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  gitsumu:
    git:
      url: https://github.com/realth000/gitsumu.git
      ref: 927a949985f131e27f401287e7915b832f24b301
  go_router: ^12.1.1
  hooks_riverpod: ^3.0.0-dev.0
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  responsive_framework: ^1.1.1
  riverpod_annotation: ^3.0.0-dev.0
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  surf_lint_rules: ^3.0.0
  toastification: ^1.1.0
  universal_html: ^2.2.4
  url_launcher: ^6.2.1
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.0-dev.8
  riverpod_lint: ^3.0.0-dev.1
  slang_build_runner: ^3.25.0

dependency_overrides:
  # Blocked by custom_lint 0.5.3
  uuid: ^4.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/tsdm_client.png"
  windows:
    generate: true
    image_path: "assets/images/tsdm_client.png"

